// Copyright (c) 2026 Halleluyah Oludele
// Licensed under the MIT License.

package pdfgrab_test

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hallelx2/pdfgrab"
)

// Golden-file tests against pdfplumber output. The expected JSON files
// in testdata/golden are generated by scripts/gen_golden.py running the
// reference pdfplumber library on the same fixture PDFs. We assert
// that pdfgrab's output matches the algorithm-level behaviour of
// pdfplumber: word count, word text, word order, and word direction
// are exact. Horizontal positions now match to 0.01pt — both libraries
// resolve standard-14 glyph widths from the same Adobe AFM metrics.
// Vertical positions do not yet; see the tolerance comment in
// compareWords and the "Parity with pdfplumber" section of the README.
//
// Tolerances:
//
//   - Word count: must match EXACTLY.
//   - Word text: must match EXACTLY (byte-equal).
//   - Word direction: must match EXACTLY.
//   - Word bbox X: ±0.01 PDF points. Measured drift is exactly 0.0000pt
//     now the standard-14 AFM widths are bundled.
//   - Word bbox Y: ±6 PDF points, and that is a KNOWN DEFECT rather than
//     an acceptance threshold — standard-14 fonts ship no
//     /FontDescriptor either, so Ascent/Descent are missing and every
//     glyph box sits descent*size too high.
//
// extract_text() is compared as a sequence of whitespace-separated
// words (order + text), absorbing spacing differences that come from
// the same font-metric origin.

type goldenWord struct {
	Text      string  `json:"text"`
	X0        float64 `json:"x0"`
	X1        float64 `json:"x1"`
	Y0        float64 `json:"y0"`
	Y1        float64 `json:"y1"`
	Upright   bool    `json:"upright"`
	Direction string  `json:"direction"`
}

type goldenPage struct {
	Number       int          `json:"number"`
	Width        float64      `json:"width"`
	Height       float64      `json:"height"`
	ExtractText  string       `json:"extract_text"`
	ExtractWords []goldenWord `json:"extract_words"`
}

type golden struct {
	Name  string       `json:"name"`
	Pages []goldenPage `json:"pages"`
}

// TestGoldenAgainstPdfplumber loads each fixture, runs the pdfgrab
// extraction, and diffs against the pre-generated pdfplumber output.
func TestGoldenAgainstPdfplumber(t *testing.T) {
	dir := filepath.Join("testdata", "golden")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read golden dir: %v", err)
	}

	// Find every .expected.json (but NOT one of the table goldens —
	// those have a different schema and are exercised by the
	// strategy-specific TestGoldenTables* tests below) and run a
	// sub-test for each.
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".expected.json") {
			continue
		}
		if strings.HasSuffix(name, ".tables.expected.json") {
			continue
		}
		if strings.HasSuffix(name, ".tables-text.expected.json") {
			continue
		}
		stem := strings.TrimSuffix(name, ".expected.json")
		t.Run(stem, func(t *testing.T) {
			runGoldenCase(t, dir, stem)
		})
	}
}

// goldenTables is the schema written by scripts/gen_golden_tables.py
// (or the inline snippet documented in CHANGELOG / README) — one
// entry per page, with the page's `find_tables(...)` output captured
// as a [][][]string per table.
//
// Cells in pdfplumber's output that contain "\n" run their cell text
// across multiple visual lines; we compare after whitespace
// normalisation so the Go output (which assembles cell text via the
// dense extract_text path) is allowed to use either "\n" or " " as
// the intra-cell separator. The token sequence must match exactly.
type goldenTables struct {
	Name  string             `json:"name"`
	Pages []goldenTablesPage `json:"pages"`
}

type goldenTablesPage struct {
	Number int          `json:"number"`
	Width  float64      `json:"width"`
	Height float64      `json:"height"`
	Tables [][][]string `json:"tables"`
}

// TestGoldenTablesAgainstPdfplumber runs ExtractTables against each
// fixture and asserts the table count, row count, column count, and
// cell text (after whitespace normalisation) matches pdfplumber's
// reference output.
//
// Pdfplumber occasionally produces cells whose text contains "\n"
// (from intra-cell line breaks); our dense extract_text path joins
// chars on the same visual line with spaces and lines with newlines,
// so a 3-line cell in pdfplumber might be "A\nB\nC" while we
// produce "A B C". We normalise both sides by collapsing runs of
// whitespace into a single space and stripping leading/trailing
// space.
func TestGoldenTablesAgainstPdfplumber(t *testing.T) {
	dir := filepath.Join("testdata", "golden")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read golden dir: %v", err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".tables.expected.json") {
			continue
		}
		stem := strings.TrimSuffix(name, ".tables.expected.json")
		t.Run(stem, func(t *testing.T) {
			runGoldenTablesCase(t, dir, stem, pdfgrab.DefaultTableSettings())
		})
	}
}

// TestGoldenTablesTextStrategyAgainstPdfplumber asserts pdfgrab's
// "text" strategy output matches pdfplumber's
// find_tables({"text", "text"}) on every .tables-text.expected.json
// fixture in testdata/golden. The strategy-specific suffix lets us
// pin the parity expectation per fixture independently of the
// default-lines test above.
func TestGoldenTablesTextStrategyAgainstPdfplumber(t *testing.T) {
	dir := filepath.Join("testdata", "golden")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read golden dir: %v", err)
	}
	settings := pdfgrab.DefaultTableSettings()
	settings.VerticalStrategy = pdfgrab.StrategyText
	settings.HorizontalStrategy = pdfgrab.StrategyText
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".tables-text.expected.json") {
			continue
		}
		stem := strings.TrimSuffix(name, ".tables-text.expected.json")
		t.Run(stem, func(t *testing.T) {
			runGoldenTablesCaseSuffix(t, dir, stem, ".tables-text.expected.json", settings)
		})
	}
}

func runGoldenTablesCase(t *testing.T, dir, stem string, settings pdfgrab.TableSettings) {
	t.Helper()
	runGoldenTablesCaseSuffix(t, dir, stem, ".tables.expected.json", settings)
}

func runGoldenTablesCaseSuffix(t *testing.T, dir, stem, suffix string, settings pdfgrab.TableSettings) {
	t.Helper()
	pdfPath := filepath.Join(dir, stem+".pdf")
	jsonPath := filepath.Join(dir, stem+suffix)

	data, err := os.ReadFile(jsonPath)
	if err != nil {
		t.Fatalf("read %s: %v", jsonPath, err)
	}
	var g goldenTables
	if err := json.Unmarshal(data, &g); err != nil {
		t.Fatalf("parse %s: %v", jsonPath, err)
	}

	doc, err := pdfgrab.OpenFile(pdfPath)
	if err != nil {
		t.Fatalf("OpenFile %s: %v", pdfPath, err)
	}
	defer doc.Close()

	for _, expPage := range g.Pages {
		p, err := doc.Page(expPage.Number)
		if err != nil {
			t.Fatalf("Page(%d): %v", expPage.Number, err)
		}
		gotTables, err := p.ExtractTables(settings)
		if err != nil {
			t.Fatalf("ExtractTables: %v", err)
		}
		if len(gotTables) != len(expPage.Tables) {
			t.Fatalf("page %d: got %d tables, want %d",
				expPage.Number, len(gotTables), len(expPage.Tables))
		}
		for ti := range expPage.Tables {
			wantTable := expPage.Tables[ti]
			gotTable := gotTables[ti]
			if len(gotTable.Rows) != len(wantTable) {
				t.Errorf("page %d table %d: rows got %d, want %d",
					expPage.Number, ti, len(gotTable.Rows), len(wantTable))
				continue
			}
			for ri := range wantTable {
				if len(gotTable.Rows[ri]) != len(wantTable[ri]) {
					t.Errorf("page %d table %d row %d: cols got %d, want %d",
						expPage.Number, ti, ri, len(gotTable.Rows[ri]), len(wantTable[ri]))
					continue
				}
				for ci := range wantTable[ri] {
					got := normaliseCellText(gotTable.Rows[ri][ci])
					want := normaliseCellText(wantTable[ri][ci])
					if got != want {
						t.Errorf("page %d table %d cell [%d][%d]: got %q, want %q",
							expPage.Number, ti, ri, ci, got, want)
					}
				}
			}
		}
	}
}

// normaliseCellText collapses runs of whitespace into single spaces
// and strips leading / trailing whitespace. Used to compare
// pdfgrab's cell output against pdfplumber's: both sides should
// agree on the token sequence even if the intra-cell line break
// convention differs.
func normaliseCellText(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func runGoldenCase(t *testing.T, dir, stem string) {
	t.Helper()

	pdfPath := filepath.Join(dir, stem+".pdf")
	jsonPath := filepath.Join(dir, stem+".expected.json")

	data, err := os.ReadFile(jsonPath)
	if err != nil {
		t.Fatalf("read %s: %v", jsonPath, err)
	}
	var g golden
	if err := json.Unmarshal(data, &g); err != nil {
		t.Fatalf("parse %s: %v", jsonPath, err)
	}

	doc, err := pdfgrab.OpenFile(pdfPath)
	if err != nil {
		t.Fatalf("OpenFile %s: %v", pdfPath, err)
	}
	defer doc.Close()

	if doc.NumPages() != len(g.Pages) {
		t.Fatalf("page count: got %d, want %d", doc.NumPages(), len(g.Pages))
	}

	for _, expPage := range g.Pages {
		p, err := doc.Page(expPage.Number)
		if err != nil {
			t.Fatalf("Page(%d): %v", expPage.Number, err)
		}

		// Page dimensions should match exactly (these come from the
		// MediaBox, not from font metrics).
		if math.Abs(p.Width()-expPage.Width) > 0.01 {
			t.Errorf("page %d width: got %v, want %v", expPage.Number, p.Width(), expPage.Width)
		}
		if math.Abs(p.Height()-expPage.Height) > 0.01 {
			t.Errorf("page %d height: got %v, want %v", expPage.Number, p.Height(), expPage.Height)
		}

		gotWords, err := p.Words(pdfgrab.DefaultWordOpts())
		if err != nil {
			t.Fatalf("Words: %v", err)
		}
		assertGoldenWords(t, expPage.Number, gotWords, expPage.ExtractWords)

		// Dense extract_text should produce the same word *sequence*
		// when split on whitespace. We don't compare byte-equal because
		// pdfplumber sometimes inserts extra spaces for vertical jitter
		// that our YTolerance clustering smooths over.
		gotText, err := p.ExtractText(pdfgrab.DefaultTextOpts())
		if err != nil {
			t.Fatalf("ExtractText: %v", err)
		}
		assertWordSequence(t, expPage.Number, gotText, expPage.ExtractText)
	}
}

func assertGoldenWords(t *testing.T, page int, got []pdfgrab.Word, want []goldenWord) {
	t.Helper()
	if len(got) != len(want) {
		t.Errorf("page %d: got %d words, want %d", page, len(got), len(want))
		// Print first few mismatches for debugging.
		n := len(got)
		if len(want) > n {
			n = len(want)
		}
		if n > 6 {
			n = 6
		}
		for i := 0; i < n; i++ {
			var gs, ws string
			if i < len(got) {
				gs = fmt.Sprintf("%q@(%.1f,%.1f)-(%.1f,%.1f)", got[i].Text, got[i].X0, got[i].Y0, got[i].X1, got[i].Y1)
			}
			if i < len(want) {
				ws = fmt.Sprintf("%q@(%.1f,%.1f)-(%.1f,%.1f)", want[i].Text, want[i].X0, want[i].Y0, want[i].X1, want[i].Y1)
			}
			t.Logf("  [%d] got=%s want=%s", i, gs, ws)
		}
		return
	}

	// Position tolerances, split by axis because the two axes are in
	// different states.
	//
	// HORIZONTAL is solved. This was 15pt while pdfgrab guessed a flat
	// 500/1000 width for standard-14 fonts shipping no /Widths array;
	// measured X drift against these fixtures was then 11.99pt max /
	// 4.79pt mean. With the Adobe Core 14 AFM widths bundled it is
	// exactly 0.0000pt — pdfgrab and pdfplumber agree bit-for-bit. 0.01
	// matches the page-dimension tolerance above and leaves room for
	// nothing but float noise. Deliberately tight: at 15pt this
	// assertion would still pass if the widths regressed all the way
	// back to the flat guess, which is the bug it exists to catch.
	//
	// VERTICAL is now solved too. It previously sat at 6pt documenting a
	// known defect: the same standard-14 exemption that omits /Widths
	// also omits /FontDescriptor, so Ascent/Descent were 0 and the glyph
	// box collapsed to [baseline, baseline+size] instead of resting on
	// the real descender. Every box sat descent*size too high — measured
	// at 2.484pt for 12pt text and 4.968pt for 24pt, both exactly
	// 0.207*size, Helvetica's -207/1000 descender.
	//
	// Two causes, both fixed: the AFM vertical metrics are now bundled,
	// and the descent was being scaled by 0.001 but not by the font size,
	// so even a font that DID supply a descriptor got a descender
	// contribution short by a factor of the font size.
	//
	// Both axes now measure 0.0000pt against pdfplumber.
	const posTolX = 0.01 // PDF points
	const posTolY = 0.01 // PDF points
	for i := range want {
		g := got[i]
		w := want[i]
		if g.Text != w.Text {
			t.Errorf("page %d word %d: text got %q, want %q", page, i, g.Text, w.Text)
			continue
		}
		if math.Abs(g.X0-w.X0) > posTolX {
			t.Errorf("page %d word %d (%q): X0 got %v, want %v", page, i, g.Text, g.X0, w.X0)
		}
		if math.Abs(g.X1-w.X1) > posTolX {
			t.Errorf("page %d word %d (%q): X1 got %v, want %v", page, i, g.Text, g.X1, w.X1)
		}
		if math.Abs(g.Y0-w.Y0) > posTolY {
			t.Errorf("page %d word %d (%q): Y0 got %v, want %v", page, i, g.Text, g.Y0, w.Y0)
		}
		if math.Abs(g.Y1-w.Y1) > posTolY {
			t.Errorf("page %d word %d (%q): Y1 got %v, want %v", page, i, g.Text, g.Y1, w.Y1)
		}
		if g.Upright != w.Upright {
			t.Errorf("page %d word %d (%q): Upright got %v, want %v", page, i, g.Text, g.Upright, w.Upright)
		}
		if g.Direction != w.Direction {
			t.Errorf("page %d word %d (%q): Direction got %q, want %q", page, i, g.Text, g.Direction, w.Direction)
		}
	}
}

// assertWordSequence splits both strings on whitespace and compares the
// resulting word lists. Spacing differences and newlines are absorbed.
func assertWordSequence(t *testing.T, page int, got, want string) {
	t.Helper()
	gotWords := strings.Fields(got)
	wantWords := strings.Fields(want)
	if len(gotWords) != len(wantWords) {
		t.Errorf("page %d: extract_text word count: got %d %v, want %d %v",
			page, len(gotWords), gotWords, len(wantWords), wantWords)
		return
	}
	for i := range wantWords {
		if gotWords[i] != wantWords[i] {
			t.Errorf("page %d: extract_text[%d] got %q, want %q",
				page, i, gotWords[i], wantWords[i])
		}
	}
}
