// Copyright (c) 2026 Halleluyah Oludele
// Licensed under the MIT License.

package pdftable_test

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hallelx2/pdftable"
)

// Golden-file tests against pdfplumber output. The expected JSON files
// in testdata/golden are generated by scripts/gen_golden.py running the
// reference pdfplumber library on the same fixture PDFs. We assert
// that pdftable's output matches the algorithm-level behaviour of
// pdfplumber: word count, word text, word order, and word direction
// are exact; word positions are checked with a tolerance wide enough
// to absorb known font-metric drift (we use 1000-units-per-em default
// fallback for standard fonts whose AFM tables we don't bundle yet;
// pdfplumber uses pdfminer.six's bundled AFM metrics). See AGENT A's
// v0.0.1 report and the "Parity with pdfplumber" section of the
// README for the up-to-date list of metric differences.
//
// Tolerances:
//
//   - Word count: must match EXACTLY.
//   - Word text: must match EXACTLY (byte-equal).
//   - Word direction: must match EXACTLY.
//   - Word bbox: ±15 PDF points to absorb font-width drift. Tightening
//     this tolerance is a v0.2.x goal once we bundle the standard-14
//     AFM metrics.
//
// extract_text() is compared as a sequence of whitespace-separated
// words (order + text), absorbing spacing differences that come from
// the same font-metric origin.

type goldenWord struct {
	Text      string  `json:"text"`
	X0        float64 `json:"x0"`
	X1        float64 `json:"x1"`
	Y0        float64 `json:"y0"`
	Y1        float64 `json:"y1"`
	Upright   bool    `json:"upright"`
	Direction string  `json:"direction"`
}

type goldenPage struct {
	Number       int          `json:"number"`
	Width        float64      `json:"width"`
	Height       float64      `json:"height"`
	ExtractText  string       `json:"extract_text"`
	ExtractWords []goldenWord `json:"extract_words"`
}

type golden struct {
	Name  string       `json:"name"`
	Pages []goldenPage `json:"pages"`
}

// TestGoldenAgainstPdfplumber loads each fixture, runs the pdftable
// extraction, and diffs against the pre-generated pdfplumber output.
func TestGoldenAgainstPdfplumber(t *testing.T) {
	dir := filepath.Join("testdata", "golden")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read golden dir: %v", err)
	}

	// Find every .expected.json and run a sub-test for each.
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".expected.json") {
			continue
		}
		stem := strings.TrimSuffix(name, ".expected.json")
		t.Run(stem, func(t *testing.T) {
			runGoldenCase(t, dir, stem)
		})
	}
}

func runGoldenCase(t *testing.T, dir, stem string) {
	t.Helper()

	pdfPath := filepath.Join(dir, stem+".pdf")
	jsonPath := filepath.Join(dir, stem+".expected.json")

	data, err := os.ReadFile(jsonPath)
	if err != nil {
		t.Fatalf("read %s: %v", jsonPath, err)
	}
	var g golden
	if err := json.Unmarshal(data, &g); err != nil {
		t.Fatalf("parse %s: %v", jsonPath, err)
	}

	doc, err := pdftable.OpenFile(pdfPath)
	if err != nil {
		t.Fatalf("OpenFile %s: %v", pdfPath, err)
	}
	defer doc.Close()

	if doc.NumPages() != len(g.Pages) {
		t.Fatalf("page count: got %d, want %d", doc.NumPages(), len(g.Pages))
	}

	for _, expPage := range g.Pages {
		p, err := doc.Page(expPage.Number)
		if err != nil {
			t.Fatalf("Page(%d): %v", expPage.Number, err)
		}

		// Page dimensions should match exactly (these come from the
		// MediaBox, not from font metrics).
		if math.Abs(p.Width()-expPage.Width) > 0.01 {
			t.Errorf("page %d width: got %v, want %v", expPage.Number, p.Width(), expPage.Width)
		}
		if math.Abs(p.Height()-expPage.Height) > 0.01 {
			t.Errorf("page %d height: got %v, want %v", expPage.Number, p.Height(), expPage.Height)
		}

		gotWords, err := p.Words(pdftable.DefaultWordOpts())
		if err != nil {
			t.Fatalf("Words: %v", err)
		}
		assertGoldenWords(t, expPage.Number, gotWords, expPage.ExtractWords)

		// Dense extract_text should produce the same word *sequence*
		// when split on whitespace. We don't compare byte-equal because
		// pdfplumber sometimes inserts extra spaces for vertical jitter
		// that our YTolerance clustering smooths over.
		gotText, err := p.ExtractText(pdftable.DefaultTextOpts())
		if err != nil {
			t.Fatalf("ExtractText: %v", err)
		}
		assertWordSequence(t, expPage.Number, gotText, expPage.ExtractText)
	}
}

func assertGoldenWords(t *testing.T, page int, got []pdftable.Word, want []goldenWord) {
	t.Helper()
	if len(got) != len(want) {
		t.Errorf("page %d: got %d words, want %d", page, len(got), len(want))
		// Print first few mismatches for debugging.
		n := len(got)
		if len(want) > n {
			n = len(want)
		}
		if n > 6 {
			n = 6
		}
		for i := 0; i < n; i++ {
			var gs, ws string
			if i < len(got) {
				gs = fmt.Sprintf("%q@(%.1f,%.1f)-(%.1f,%.1f)", got[i].Text, got[i].X0, got[i].Y0, got[i].X1, got[i].Y1)
			}
			if i < len(want) {
				ws = fmt.Sprintf("%q@(%.1f,%.1f)-(%.1f,%.1f)", want[i].Text, want[i].X0, want[i].Y0, want[i].X1, want[i].Y1)
			}
			t.Logf("  [%d] got=%s want=%s", i, gs, ws)
		}
		return
	}

	// Generous position tolerance to absorb font-metric drift. The
	// algorithm-level outputs (text, count, order, direction) below
	// are still asserted exactly; the position checks here are a
	// regression guard against catastrophic mis-placement, not a
	// pixel-level parity check.
	const posTol = 15.0 // PDF points
	for i := range want {
		g := got[i]
		w := want[i]
		if g.Text != w.Text {
			t.Errorf("page %d word %d: text got %q, want %q", page, i, g.Text, w.Text)
			continue
		}
		if math.Abs(g.X0-w.X0) > posTol {
			t.Errorf("page %d word %d (%q): X0 got %v, want %v", page, i, g.Text, g.X0, w.X0)
		}
		if math.Abs(g.X1-w.X1) > posTol {
			t.Errorf("page %d word %d (%q): X1 got %v, want %v", page, i, g.Text, g.X1, w.X1)
		}
		if math.Abs(g.Y0-w.Y0) > posTol {
			t.Errorf("page %d word %d (%q): Y0 got %v, want %v", page, i, g.Text, g.Y0, w.Y0)
		}
		if math.Abs(g.Y1-w.Y1) > posTol {
			t.Errorf("page %d word %d (%q): Y1 got %v, want %v", page, i, g.Text, g.Y1, w.Y1)
		}
		if g.Upright != w.Upright {
			t.Errorf("page %d word %d (%q): Upright got %v, want %v", page, i, g.Text, g.Upright, w.Upright)
		}
		if g.Direction != w.Direction {
			t.Errorf("page %d word %d (%q): Direction got %q, want %q", page, i, g.Text, g.Direction, w.Direction)
		}
	}
}

// assertWordSequence splits both strings on whitespace and compares the
// resulting word lists. Spacing differences and newlines are absorbed.
func assertWordSequence(t *testing.T, page int, got, want string) {
	t.Helper()
	gotWords := strings.Fields(got)
	wantWords := strings.Fields(want)
	if len(gotWords) != len(wantWords) {
		t.Errorf("page %d: extract_text word count: got %d %v, want %d %v",
			page, len(gotWords), gotWords, len(wantWords), wantWords)
		return
	}
	for i := range wantWords {
		if gotWords[i] != wantWords[i] {
			t.Errorf("page %d: extract_text[%d] got %q, want %q",
				page, i, gotWords[i], wantWords[i])
		}
	}
}
