// Copyright (c) 2026 Halleluyah Oludele
// Licensed under the MIT License.

//go:build ignore

// gen_table_fixture.go writes out the binary fixture PDFs used by the
// table-finding parity tests. The PDFs are generated by the
// testdata.TableRuled() helper (and any future ones we add) so that
// the source-of-truth for what's in the file is Go code, not a
// binary blob in git.
//
// Usage from the repo root:
//
//	go run ./scripts/gen_table_fixture.go
//
// The script is build-tag-gated so it doesn't get picked up by
// `go build ./...` and `go test ./...`. It writes:
//
//	testdata/table-2x3-ruled.pdf   — 2-col x 3-row ruled table
//
// Re-run after editing testdata/fixtures.go's TableRuled function.
// The resulting PDFs should also be checked into git so callers
// without a Go toolchain can still run the tests.
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/hallelx2/pdfgrab/testdata"
)

func main() {
	outputs := []struct {
		path string
		data []byte
	}{
		{
			path: filepath.Join("testdata", "table-2x3-ruled.pdf"),
			data: testdata.TableRuled(),
		},
		{
			path: filepath.Join("testdata", "golden", "table-3x4-borderless.pdf"),
			data: testdata.TableBorderless(),
		},
	}
	for _, o := range outputs {
		if err := os.MkdirAll(filepath.Dir(o.path), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", filepath.Dir(o.path), err)
			os.Exit(1)
		}
		if err := os.WriteFile(o.path, o.data, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", o.path, err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s (%d bytes)\n", o.path, len(o.data))
	}
}
